name: Build and deploy ASP.Net Core app to Azure Web App - AIDD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore (project folder)
        working-directory: FlightBookingSystem
        run: dotnet restore

      - name: Build (project folder)
        working-directory: FlightBookingSystem
        run: dotnet build --configuration Release

      - name: Publish (project folder)
        working-directory: FlightBookingSystem
        # Publish into a folder named 'publish' inside FlightBookingSystem
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish
          path: FlightBookingSystem/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-publish

      - name: Show files (debug)
        run: ls -la

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AIDD'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D180D63DCAE64EDABD131E21BA7044C9 }}
